#define yyFlexLexer exparse_FlexLexer

#line 4 "lexer.cc"
/* -*-C-*- */
/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

/* %- */
/* %* */


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
/* %+ */
#ifdef __CPLUSPLUS
#define FLEX_STD   std::
#endif
#include <iostream>
/* %* */
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)


#ifdef YY_REENTRANT

/* For use wherever a Global is accessed or assigned. */
#define YY_G(var) (((struct yy_globals_t*)yy_globals)->var)

/* For use in function prototypes to append the additional argument. */
#ifdef YY_USE_PROTOS
#define YY_LAST_ARG , void * yy_globals
#define YY_ONLY_ARG    void * yy_globals
#else
#define YY_LAST_ARG , yy_globals
#define YY_ONLY_ARG    yy_globals
#define YY_DECL_LAST_ARG void * yy_globals;
#endif

/* For use in function calls to pass the additional argument. */
#define YY_CALL_LAST_ARG  , yy_globals
#define YY_CALL_ONLY_ARG   yy_globals

/* For convenience. */
#define yyin_r YY_G(yyin)
#define yyout_r YY_G(yyout)
#define yyextra_r YY_G(yyextra)
#define yyleng_r YY_G(yyleng)
#define yytext_r YY_G(yytext)
#define yylineno_r YY_G(yylineno)

int yylex_init YY_PROTO((void** scanner));
int yylex_destroy YY_PROTO((void* scanner));

#else /* not YY_REENTRANT */

  /* Define these macros to be no-ops. */
#define YY_G(var) (var)
#define YY_LAST_ARG
#define YY_ONLY_ARG  void
#define YY_CALL_LAST_ARG
#define YY_CALL_ONLY_ARG
#define YY_DECL_LAST_ARG
#endif

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN YY_G(yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((YY_G(yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( YY_G(yyin) YY_CALL_LAST_ARG )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#ifndef YY_REENTRANT
extern size_t yyleng;
#endif

/* %- */
/* %* */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = YY_G(yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		YY_G(yy_c_buf_p) = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr YY_CALL_LAST_ARG )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
/* %- */
/* %+ */
	FLEX_STD istream* yy_input_file;
/* %* */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

/* %- Standard (non-C++) definition */
/* %c */
#ifndef exparse_IN_HEADER
/* %e */
#endif /* !exparse_IN_HEADER */
/* %* */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* %- Standard (non-C++) definition */
/* %c */
#ifndef exparse_IN_HEADER
/* %e */
#endif /* !exparse_IN_HEADER */
/* %* */

/* %c */
#ifndef exparse_IN_HEADER
static void *yy_flex_alloc YY_PROTO(( yy_size_t YY_LAST_ARG ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t YY_LAST_ARG ));
static void yy_flex_free YY_PROTO(( void * YY_LAST_ARG ));
/* %e */
#endif /* !exparse_IN_HEADER */

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_G(yy_current_buffer) ) \
		YY_G(yy_current_buffer) =    \
            yy_create_buffer( YY_G(yyin), YY_BUF_SIZE YY_CALL_LAST_ARG); \
	YY_G(yy_current_buffer)->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_G(yy_current_buffer) ) \
		YY_G(yy_current_buffer) =    \
            yy_create_buffer( YY_G(yyin), YY_BUF_SIZE YY_CALL_LAST_ARG); \
	YY_G(yy_current_buffer)->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_G(yy_current_buffer)->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

/* %- Standard (non-C++) definition */
/* %c */
#ifndef exparse_IN_HEADER
/* %e */
#endif /* !exparse_IN_HEADER */
/* %* */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	YY_G(yyleng) = (size_t) (yy_cp - yy_bp); \
	YY_G(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	YY_G(yy_c_buf_p) = yy_cp;

/* %* */

/* %c */
#ifndef exparse_IN_HEADER
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
static yyconst short int yy_accept[82] =
    {   0,
        0,    0,   31,   29,    1,    1,   12,    5,   29,    9,
       10,   16,   13,   28,   14,   11,   17,    3,   27,   20,
       29,   21,   26,    2,   15,   29,    1,   23,   24,    8,
        3,    6,    7,    0,    3,    0,    0,    0,    0,    0,
       18,   22,   19,    2,   25,    3,    0,    3,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    4,    0,    0,    0,    0,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,   20,    1,   21,   21,   21,   21,   22,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
        1,    1,    1,   23,   21,    1,   21,   21,   21,   21,

       22,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,    1,   24,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[25] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[82] =
    {   0,
        0,    0,  144,  155,   23,   25,  125,  155,  136,  155,
      155,  127,  155,  155,  155,  125,   20,   17,  155,   38,
      121,  120,  155,   16,  155,  113,   33,  155,  155,  155,
       27,  155,  155,  121,   30,   45,  111,   31,  111,   59,
      155,  155,  155,   43,  155,   32,  110,  108,   53,   73,
       83,  103,   67,    0,   54,  102,   97,   98,   94,   56,
       74,  100,  118,   90,   82,    0,   75,   86,  132,   76,
       68,   58,   91,  113,   48,  155,  112,   44,   18,   92,
      155
    } ;

static yyconst short int yy_def[82] =
    {   0,
       81,    1,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   20,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   40,   81,
       81,   81,   81,   51,   81,   81,   81,   49,   81,   49,
       57,   81,   81,   81,   81,   63,   81,   81,   81,   61,
       81,   61,   69,   81,   81,   81,   81,   73,   81,   73,
        0
    } ;

static yyconst short int yy_nxt[180] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   24,   25,   26,   27,   27,   27,   27,   32,   34,
       44,   35,   80,   33,   27,   27,   44,   44,   36,   37,
       37,   31,   34,   39,   35,   40,   46,   38,   36,   38,
       39,   36,   40,   36,   47,   41,   47,   44,   78,   48,
       50,   50,   78,   44,   44,   81,   56,   49,   57,   51,
       60,   52,   72,   40,   50,   50,   59,   81,   59,   81,
       53,   60,   72,   51,   54,   54,   81,   68,   61,   69,
       70,   71,   55,   71,   55,   56,   72,   57,   62,   62,

       73,   62,   62,   81,   70,   73,   80,   63,   60,   64,
       63,   57,   58,   81,   74,   74,   61,   58,   65,   66,
       66,   79,   48,   79,   48,   49,   80,   67,   81,   67,
       68,   76,   69,   74,   74,   46,   45,   43,   42,   31,
       30,   29,   28,   81,   75,   81,   69,   81,   81,   81,
       76,   81,   81,   77,    3,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81
    } ;

static yyconst short int yy_chk[180] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,   17,   18,
       24,   18,   79,   17,   27,   27,   24,   24,   18,   20,
       20,   31,   35,   38,   35,   38,   46,   20,   31,   20,
       20,   35,   20,   46,   36,   20,   36,   44,   78,   36,
       40,   40,   75,   44,   44,   49,   55,   49,   55,   40,
       60,   40,   72,   40,   50,   50,   53,   60,   53,   72,
       40,   53,   71,   50,   51,   51,   61,   67,   61,   67,
       70,   65,   51,   65,   51,   51,   65,   51,   57,   57,

       68,   62,   62,   73,   64,   73,   80,   57,   59,   57,
       62,   57,   58,   80,   74,   74,   56,   52,   57,   63,
       63,   77,   48,   77,   47,   39,   77,   63,   37,   63,
       63,   74,   63,   69,   69,   34,   26,   22,   21,   16,
       12,    9,    7,    3,   69,    0,   69,    0,    0,    0,
       69,    0,    0,   69,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "./lexer.ll"
#define INITIAL 0
#line 2 "./lexer.ll"
/*
 * lexer.ll
 * 
 * Expression lexer (flex source) 
 * 
 * Copyright (c) 2001 by Wolfgang Wieser (wwieser@gmx.de) 
 * 
 * This file may be distributed and/or modified under the terms of the 
 * GNU General Public License version 2 as published by the Free Software 
 * Foundation. 
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * 
 */

// Include expression tokens: 
#define exparse_in_flex_source 1
#include "lexer.hpp"

// Grrr #@/&$+\*!!! Opening a namespace here will NOT 
// put the generated class into this namespace. Damn! 
using namespace exparse;

/* unsigned float value */
/* signed float value */
/*fLAG        (on|off|yes|no|true|false|1|0)/[^[:alnum:]]*/
#line 505 "lexer.cc"
/* %e */
#endif /* !exparse_IN_HEADER */

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %- Reentrant structure and macros (non-C++). */
/* %c */
#ifndef exparse_IN_HEADER
/* %e */
#endif /* !exparse_IN_HEADER */
/* %- */
/* %c */
#ifndef exparse_IN_HEADER
/* %e */
#endif /* !exparse_IN_HEADER */
/* %* */

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int YY_LAST_ARG));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * YY_LAST_ARG));
#endif

#ifndef YY_NO_INPUT
/* %- Standard (non-C++) definition */
/* %c */
#ifndef exparse_IN_HEADER
/* %e */
#endif /* !exparse_IN_HEADER */
/* %* */
#endif

#if YY_STACK_USED
#ifndef YY_REENTRANT
/* %c */
#ifndef exparse_IN_HEADER
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
/* %e */
#endif /* !exparse_IN_HEADER */
#endif
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state YY_LAST_ARG));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( YY_ONLY_ARG ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( YY_ONLY_ARG ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* %- Standard (non-C++) definition */
/* %+ C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %* */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
/* %+ C++ definition \ */\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %* */
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %- */
/* %+ */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %* */
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
/* %- Standard (non-C++) definition */
/* %+ C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %* */
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %c */
#ifndef exparse_IN_HEADER
YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

/* %% [7.0] user's declarations go here */
#line 43 "./lexer.ll"


#line 668 "lexer.cc"

#ifdef YY_REENTRANT_BISON_PURE
    YY_G(yylval) = yylvalp;
#ifdef YYLTYPE
    YY_G(yylloc) = yyllocp;
#endif
#endif

	if ( YY_G(yy_init) )
		{
		YY_G(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! YY_G(yy_start) )
			YY_G(yy_start) = 1;	/* first start state */

		if ( ! YY_G(yyin) )
/* %- */
/* %+ */
			yyin = & FLEX_STD cin;
/* %* */

		if ( ! YY_G(yyout) )
/* %- */
/* %+ */
			yyout = & FLEX_STD cout;
/* %* */

		if ( ! YY_G(yy_current_buffer) )
			YY_G(yy_current_buffer) =
				yy_create_buffer( YY_G(yyin), YY_BUF_SIZE YY_CALL_LAST_ARG);

		yy_load_buffer_state( YY_CALL_ONLY_ARG );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = YY_G(yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = YY_G(yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = YY_G(yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				YY_G(yy_last_accepting_state) = yy_current_state;
				YY_G(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 82 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 155 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = YY_G(yy_last_accepting_cpos);
			yy_current_state = YY_G(yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = YY_G(yy_hold_char);
			yy_cp = YY_G(yy_last_accepting_cpos);
			yy_current_state = YY_G(yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 45 "./lexer.ll"
return(TWSpace);  /* whitespace */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "./lexer.ll"
return(TIdentifier);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "./lexer.ll"
return(TVScalar);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "./lexer.ll"
return(TVVector);
	YY_BREAK
/*{fLAG}              return(TVFlag);*/
case 5:
YY_RULE_SETUP
#line 50 "./lexer.ll"
return(TVString);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "./lexer.ll"
return(TCComment);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "./lexer.ll"
return(TCppComment);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "./lexer.ll"
return(TCCommentEnd);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 54 "./lexer.ll"
return(TEOF);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "./lexer.ll"
return(TEOpBr);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "./lexer.ll"
return(TEClBr);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 58 "./lexer.ll"
return(TEDot);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 59 "./lexer.ll"
return(TENot);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "./lexer.ll"
return(TEPlus);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "./lexer.ll"
return(TEMinus);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "./lexer.ll"
return(TEPow);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "./lexer.ll"
return(TEMul);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "./lexer.ll"
return(TEDiv);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "./lexer.ll"
return(TELE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "./lexer.ll"
return(TEGE);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "./lexer.ll"
return(TEL);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 68 "./lexer.ll"
return(TEG);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 69 "./lexer.ll"
return(TEEq);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 70 "./lexer.ll"
return(TENEq);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 71 "./lexer.ll"
return(TEAnd);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 72 "./lexer.ll"
return(TEOr);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 73 "./lexer.ll"
return(TECondQ);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 74 "./lexer.ll"
return(TECondC);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 75 "./lexer.ll"
return(TESep);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 77 "./lexer.ll"
return(TUnknown);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "./lexer.ll"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 925 "lexer.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = YY_G(yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_G(yy_current_buffer)->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_n_chars;
			YY_G(yy_current_buffer)->yy_input_file = YY_G(yyin);
			YY_G(yy_current_buffer)->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( YY_G(yy_c_buf_p) <= &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			YY_G(yy_c_buf_p) = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state YY_CALL_LAST_ARG);

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++YY_G(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = YY_G(yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( YY_CALL_ONLY_ARG ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				YY_G(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( YY_CALL_ONLY_ARG ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					YY_G(yy_c_buf_p) = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! YY_G(yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				YY_G(yy_c_buf_p) =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

				yy_cp = YY_G(yy_c_buf_p);
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				YY_G(yy_c_buf_p) =
				&YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)];

				yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

				yy_cp = YY_G(yy_c_buf_p);
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */
/* %e */
#endif /* !exparse_IN_HEADER */
/* %+ */
/* %c */
#ifndef exparse_IN_HEADER
yyFlexLexer::yyFlexLexer( FLEX_STD istream* arg_yyin, FLEX_STD ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete [] yy_state_buf;
	yy_flex_free( yy_start_stack YY_CALL_LAST_ARG );
	yy_delete_buffer( yy_current_buffer YY_CALL_LAST_ARG);
	}

void yyFlexLexer::switch_streams( FLEX_STD  istream* new_in, FLEX_STD ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer  YY_CALL_LAST_ARG);
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  YY_CALL_LAST_ARG) YY_CALL_LAST_ARG);
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}
/* %e */
#endif /* !exparse_IN_HEADER */
/* %* */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

/* %- */
/* %c */
#ifndef exparse_IN_HEADER
/* %+ */
int yyFlexLexer::yy_get_next_buffer()
/* %* */
	{
	register char *dest = YY_G(yy_current_buffer)->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( YY_G(yy_c_buf_p) > &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_G(yy_current_buffer)->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( YY_G(yy_c_buf_p) - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (YY_G(yy_c_buf_p) - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_G(yy_current_buffer)->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_G(yy_current_buffer)->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_G(yy_current_buffer);

			int yy_c_buf_p_offset =
				(int) (YY_G(yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 YY_CALL_LAST_ARG );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			YY_G(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_G(yy_current_buffer)->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_G(yy_current_buffer)->yy_ch_buf[number_to_move]),
			YY_G(yy_n_chars), num_to_read );

		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars);
		}

	if ( YY_G(yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( YY_G(yyin)  YY_CALL_LAST_ARG);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_G(yy_current_buffer)->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	YY_G(yy_n_chars) += number_to_move;
	YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &YY_G(yy_current_buffer)->yy_ch_buf[0];

	return ret_val;
	}
/* %e */
#endif /* !exparse_IN_HEADER */

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %- */
/* %c */
#ifndef exparse_IN_HEADER
/* %+ */
yy_state_type yyFlexLexer::yy_get_previous_state()
/* %* */
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = YY_G(yy_start);

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < YY_G(yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			YY_G(yy_last_accepting_state) = yy_current_state;
			YY_G(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 82 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

/* %- */
/* %+ */
yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %* */
	{
	register int yy_is_jam;
/* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = YY_G(yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		YY_G(yy_last_accepting_state) = yy_current_state;
		YY_G(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 82 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 81);

	return yy_is_jam ? 0 : yy_current_state;
	}


/* %- */
/* %+ */
void yyFlexLexer::yyunput( int c, register char* yy_bp YY_LAST_ARG)
/* %* */
	{
	register char *yy_cp = YY_G(yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = YY_G(yy_hold_char);

	if ( yy_cp < YY_G(yy_current_buffer)->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = YY_G(yy_n_chars) + 2;
		register char *dest = &YY_G(yy_current_buffer)->yy_ch_buf[
					YY_G(yy_current_buffer)->yy_buf_size + 2];
		register char *source =
				&YY_G(yy_current_buffer)->yy_ch_buf[number_to_move];

		while ( source > YY_G(yy_current_buffer)->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_G(yy_current_buffer)->yy_n_chars =
			YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_buf_size;

		if ( yy_cp < YY_G(yy_current_buffer)->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	yytext_ptr = yy_bp;
	YY_G(yy_hold_char) = *yy_cp;
	YY_G(yy_c_buf_p) = yy_cp;
	}
/* %- */
/* %* */


/* %- */
/* %+ */
int yyFlexLexer::yyinput()
/* %* */
	{
	int c;

	*YY_G(yy_c_buf_p) = YY_G(yy_hold_char);

	if ( *YY_G(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( YY_G(yy_c_buf_p) < &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] )
			/* This was really a NUL. */
			*YY_G(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = YY_G(yy_c_buf_p) - yytext_ptr;
			++YY_G(yy_c_buf_p);

			switch ( yy_get_next_buffer( YY_CALL_ONLY_ARG ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( YY_G(yyin) YY_CALL_LAST_ARG);

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( YY_CALL_ONLY_ARG ) )
						return EOF;

					if ( ! YY_G(yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(YY_CALL_ONLY_ARG);
#else
					return input(YY_CALL_ONLY_ARG);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					YY_G(yy_c_buf_p) = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) YY_G(yy_c_buf_p);	/* cast for 8-bit char's */
	*YY_G(yy_c_buf_p) = '\0';	/* preserve yytext */
	YY_G(yy_hold_char) = *++YY_G(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
	}
/* %- */
/* %* */

/* %- */
/* %+ */
void yyFlexLexer::yyrestart( FLEX_STD istream* input_file )
/* %* */
	{
	if ( ! YY_G(yy_current_buffer) )
		YY_G(yy_current_buffer) =
            yy_create_buffer( YY_G(yyin), YY_BUF_SIZE YY_CALL_LAST_ARG);

	yy_init_buffer( YY_G(yy_current_buffer), input_file YY_CALL_LAST_ARG);
	yy_load_buffer_state( YY_CALL_ONLY_ARG );
	}


/* %- */
/* %+ */
void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %* */
	{
	if ( YY_G(yy_current_buffer) == new_buffer )
		return;

	if ( YY_G(yy_current_buffer) )
		{
		/* Flush out information for old buffer. */
		*YY_G(yy_c_buf_p) = YY_G(yy_hold_char);
		YY_G(yy_current_buffer)->yy_buf_pos = YY_G(yy_c_buf_p);
		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars);
		}

	YY_G(yy_current_buffer) = new_buffer;
	yy_load_buffer_state( YY_CALL_ONLY_ARG );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	YY_G(yy_did_buffer_switch_on_eof) = 1;
	}


/* %- */
/* %+ */
void yyFlexLexer::yy_load_buffer_state()
/* %* */
	{
	YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_n_chars;
	yytext_ptr = YY_G(yy_c_buf_p) = YY_G(yy_current_buffer)->yy_buf_pos;
	YY_G(yyin) = YY_G(yy_current_buffer)->yy_input_file;
	YY_G(yy_hold_char) = *YY_G(yy_c_buf_p);
	}


/* %- */
/* %+ */
YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( FLEX_STD istream* file, int size )
/* %* */
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) YY_CALL_LAST_ARG );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 YY_CALL_LAST_ARG );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file YY_CALL_LAST_ARG);

	return b;
	}


/* %- */
/* %+ */
void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %* */
	{
	if ( ! b )
		return;

	if ( b == YY_G(yy_current_buffer) )
		YY_G(yy_current_buffer) = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf YY_CALL_LAST_ARG );

	yy_flex_free( (void *) b YY_CALL_LAST_ARG );
	}


/* %- */
/* %+ */
#ifndef YY_NEVER_INTERACTIVE
extern "C" int isatty YY_PROTO(( int )) THROW_NIL ;
#endif
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, FLEX_STD istream* file )
/* %* */

	{
	int oerrno = errno;

	yy_flush_buffer( b YY_CALL_LAST_ARG);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

/* %- */
/* %+ */
	b->yy_is_interactive = 0;
/* %* */
	errno = oerrno;
	}


/* %- */
/* %+ */
void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %* */
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_G(yy_current_buffer) )
		yy_load_buffer_state( YY_CALL_ONLY_ARG );
	}
/* %* */


#ifndef YY_NO_SCAN_BUFFER
/* %- */
/* %* */
#endif


#ifndef YY_NO_SCAN_STRING
/* %- */
/* %* */
#endif


#ifndef YY_NO_SCAN_BYTES
/* %- */
/* %* */
#endif


#ifndef YY_NO_PUSH_STATE
/* %- */
/* %+ */
void yyFlexLexer::yy_push_state( int new_state )
/* %* */
	{
	if ( YY_G(yy_start_stack_ptr) >= YY_G(yy_start_stack_depth) )
		{
		yy_size_t new_size;

		YY_G(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = YY_G(yy_start_stack_depth) * sizeof( int );

		if ( ! YY_G(yy_start_stack) )
			YY_G(yy_start_stack) = (int *) yy_flex_alloc( new_size YY_CALL_LAST_ARG );

		else
			YY_G(yy_start_stack) = (int *) yy_flex_realloc(
					(void *) YY_G(yy_start_stack), new_size YY_CALL_LAST_ARG );

		if ( ! YY_G(yy_start_stack) )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
/* %- */
/* %+ */
void yyFlexLexer::yy_pop_state()
/* %* */
	{
	if ( --YY_G(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr)]);
	}
#endif


#ifndef YY_NO_TOP_STATE
/* %- */
/* %+ */
int yyFlexLexer::yy_top_state()
/* %* */
	{
	return YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr) - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %- */
/* %+ */

void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	FLEX_STD cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}
/* %* */


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		YY_G(yytext)[YY_G(yyleng)] = YY_G(yy_hold_char); \
		YY_G(yy_c_buf_p) = YY_G(yytext) + n; \
		YY_G(yy_hold_char) = *YY_G(yy_c_buf_p); \
		*YY_G(yy_c_buf_p) = '\0'; \
		YY_G(yyleng) = n; \
		} \
	while ( 0 )



#ifdef YY_REENTRANT

/* Accessor  methods (get/set functions) to struct members. */

#ifndef YY_NO_GET_EXTRA
#ifdef YY_USE_PROTOS
YY_EXTRA_TYPE yyget_extra( YY_ONLY_ARG )
#else
YY_EXTRA_TYPE yyget_extra( YY_ONLY_ARG )
    YY_DECL_LAST_ARG
#endif
{
    return YY_G(yyextra);
}
#endif /* !YY_NO_GET_EXTRA */

#ifndef YY_NO_GET_LINENO
#  ifdef YY_USE_PROTOS
int yyget_lineno( YY_ONLY_ARG )
#  else
int yyget_lineno( YY_ONLY_ARG )
    YY_DECL_LAST_ARG
#  endif
{
    return YY_G(yylineno);
}
#endif /* !YY_NO_GET_LINENO */

#ifndef YY_NO_GET_IN
#ifdef YY_USE_PROTOS
FILE *yyget_in( YY_ONLY_ARG )
#else
FILE *yyget_in( YY_ONLY_ARG )
    YY_DECL_LAST_ARG
#endif
{
    return YY_G(yyin);
}
#endif /* !YY_NO_GET_IN */

#ifndef YY_NO_GET_OUT
#ifdef YY_USE_PROTOS
FILE *yyget_out( YY_ONLY_ARG )
#else
FILE *yyget_out( YY_ONLY_ARG )
    YY_DECL_LAST_ARG
#endif
{
    return YY_G(yyout);
}
#endif /* !YY_NO_GET_OUT */

#ifndef YY_NO_GET_LENG
#ifdef YY_USE_PROTOS
int yyget_leng( YY_ONLY_ARG )
#else
int yyget_leng( YY_ONLY_ARG )
    YY_DECL_LAST_ARG
#endif
{
    return YY_G(yyleng);
}
#endif /* !YY_NO_GET_LENG */

#ifndef YY_NO_GET_TEXT
#ifdef YY_USE_PROTOS
char *yyget_text( YY_ONLY_ARG )
#else
char *yyget_text( YY_ONLY_ARG )
    YY_DECL_LAST_ARG
#endif
{
    return YY_G(yytext);
}
#endif /* !YY_NO_GET_TEXT */

#ifndef YY_NO_SET_EXTRA
#ifdef YY_USE_PROTOS
void yyset_extra( YY_EXTRA_TYPE user_defined YY_LAST_ARG )
#else
void yyset_extra( user_defined YY_LAST_ARG )
    YY_EXTRA_TYPE user_defined;
    YY_DECL_LAST_ARG
#endif
{
    YY_G(yyextra) = user_defined ;
}
#endif /* !YY_NO_SET_EXTRA */

#ifndef YY_NO_SET_LINENO
#  ifdef YY_USE_PROTOS
void yyset_lineno( int line_number YY_LAST_ARG )
#  else
void yyset_lineno( line_number YY_LAST_ARG )
    int line_number;
    YY_DECL_LAST_ARG
#  endif
{
    YY_G(yylineno) = line_number;
}
#endif /* !YY_NO_SET_LINENO */


#ifndef YY_NO_SET_IN
#ifdef YY_USE_PROTOS
void yyset_in( FILE * in_str YY_LAST_ARG )
#else
void yyset_in( in_str YY_LAST_ARG )
    FILE * in_str;
    YY_DECL_LAST_ARG
#endif
{
    YY_G(yyin) = in_str ;
}
#endif /* !YY_NO_SET_IN */

#ifndef YY_NO_SET_OUT
#ifdef YY_USE_PROTOS
void yyset_out( FILE * out_str YY_LAST_ARG )
#else
void yyset_out( out_str YY_LAST_ARG )
    FILE * out_str;
    YY_DECL_LAST_ARG
#endif
{
    YY_G(yyout) = out_str ;
}
#endif /* !YY_NO_SET_OUT */

/* Accessor methods for yylval and yylloc */

#ifdef YY_REENTRANT_BISON_PURE
#ifndef YY_NO_GET_LVAL
#ifdef YY_USE_PROTOS
YYSTYPE * yyget_lval( YY_ONLY_ARG )
#else
YYSTYPE * yyget_lval( YY_ONLY_ARG )
    YY_DECL_LAST_ARG
#endif
{
    return YY_G(yylval);
}
#endif /* !YY_NO_GET_LVAL */

#ifndef YY_NO_SET_LVAL
#ifdef YY_USE_PROTOS
void yyset_lval( YYSTYPE * yylvalp YY_LAST_ARG )
#else
void yyset_lval( yylvalp YY_LAST_ARG )
    YYSTYPE * yylvalp;
    YY_DECL_LAST_ARG
#endif
{
    YY_G(yylval) = yylvalp;
}
#endif /* !YY_NO_SET_LVAL */

#ifdef YYLTYPE
#ifndef YY_NO_GET_LLOC
#ifdef YY_USE_PROTOS
YYLTYPE *yyget_lloc( YY_ONLY_ARG )
#else
YYLTYPE *yyget_lloc( YY_ONLY_ARG )
    YY_DECL_LAST_ARG
#endif
{
    return YY_G(yylloc);
}
#endif /* !YY_NO_GET_LLOC */

#ifndef YY_NO_SET_LLOC
#ifdef YY_USE_PROTOS
void yyset_lloc( YYLTYPE * yyllocp YY_LAST_ARG )
#else
void yyset_lloc( yyllocp YY_LAST_ARG )
    YYLTYPE * yyllocp;
    YY_DECL_LAST_ARG
#endif
{
    YY_G(yylloc) = yyllocp;
}
#endif /* !YY_NO_SET_LLOC */

#endif /* YYLTYPE */
#endif /* YY_REENTRANT_BISON_PURE */


#ifdef YY_USE_PROTOS
static int yy_init_globals( void* yy_globals)
#else
static int yy_init_globals( yy_globals )
    void* yy_globals;
#endif
    {
    /* Initialization is the same as for the non-reentrant scanner.
       This function is called once per scanner lifetime. */

  /* We do not touch yylineno unless the option is enabled. */
#ifdef YY_USE_LINENO
    YY_G(yylineno) =  1;
#endif
    YY_G(yy_current_buffer) = 0;
    YY_G(yy_c_buf_p) = (char *) 0;
    YY_G(yy_init) = 1;
    YY_G(yy_start) = 0;
    YY_G(yy_start_stack_ptr) = 0;
    YY_G(yy_start_stack_depth) = 0;
    YY_G(yy_start_stack) = (int *) 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    YY_G(yyin) = stdin;
    YY_G(yyout) = stdout;
#else
    YY_G(yyin) = (FILE *) 0;
    YY_G(yyout) = (FILE *) 0;
#endif
    return 0;
    }

/* User-visible API */
#ifdef YY_USE_PROTOS
int yylex_init( void** ptr_yy_globals)
#else
int yylex_init( ptr_yy_globals )
    void** ptr_yy_globals;
#endif
    {
    *ptr_yy_globals = (void *) yy_flex_alloc ( sizeof( struct yy_globals_t ), NULL );
    yy_init_globals ( *ptr_yy_globals );
    return 0;
    }

#ifdef YY_USE_PROTOS
int yylex_destroy( void* yy_globals )
#else
int yylex_destroy( yy_globals )
    void* yy_globals;
#endif
    {
    if( yy_globals )
        {

            /* Destroy the current (main) buffer. */
            yy_delete_buffer( YY_G(yy_current_buffer) YY_CALL_LAST_ARG );
            YY_G(yy_current_buffer) = NULL;

            /* Destroy the start condition stack. */
            if( YY_G(yy_start_stack) ) {
                yy_flex_free( YY_G(yy_start_stack) YY_CALL_LAST_ARG );
                YY_G(yy_start_stack) = NULL;
            }

            /* Destroy the main struct. */
            yy_flex_free ( yy_globals YY_CALL_LAST_ARG );
        }
    return 0;
    }

#endif /* End YY_REENTRANT */

/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n YY_LAST_ARG)
#else
static void yy_flex_strncpy( s1, s2, n YY_LAST_ARG)
char *s1;
yyconst char *s2;
int n;
YY_DECL_LAST_ARG
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s YY_LAST_ARG)
#else
static int yy_flex_strlen( s YY_LAST_ARG)
yyconst char *s;
YY_DECL_LAST_ARG
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size YY_LAST_ARG )
#else
static void *yy_flex_alloc( size YY_LAST_ARG )
yy_size_t size;
YY_DECL_LAST_ARG
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size YY_LAST_ARG )
#else
static void *yy_flex_realloc( ptr, size YY_LAST_ARG )
void *ptr;
yy_size_t size;
YY_DECL_LAST_ARG
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr YY_LAST_ARG )
#else
static void yy_flex_free( ptr YY_LAST_ARG )
void *ptr;
YY_DECL_LAST_ARG
#endif
	{
	free( (char *) ptr );	/* see yy_flex_realloc() for (char *) cast */
	}

#if YY_MAIN
int main()
	{

#ifdef YY_REENTRANT
    void *lexer;
    yylex_init(&lexer);
    yylex( lexer );
    yylex_destroy( lexer);

#else
	yylex();
#endif

	return 0;
	}
#endif
/* %e */
#endif /* !exparse_IN_HEADER */
#line 79 "./lexer.ll"
#ifndef exparse_IN_HEADER


#endif /* !exparse_IN_HEADER */
