This is the second version of libval. 

Note that due to some template bugs in gcc-2.95.x and possibly 
all earlier versions supporting templates, this code will NOT 
compile with gcc versions prior to 3.0. On my box, I have no 
trouble compiling it with gcc-3.0.1. 

So, please don't write bug reports if gcc < 3.0 fails to compile 
this. 

Wolfgang Wieser
