#! /bin/bash

../testadlparser $1 > /dev/null 2>&1 
if test "`diff test_filled_adl.out $1.out0`" != ""; then
  echo "************************************************"
  echo "** Error: different pre results for $1" 
  echo "************************************************"
  diff test_filled_adl.out $1.out0;
  exit -1;
fi
if test "`diff final_test_filled_adl.out $1.out1`" != ""; then
  echo "************************************************"
  echo "** Error: different final results for $1"
  echo "************************************************"
  diff final_test_filled_adl.out $1.out1;
  exit -1;
fi
echo still OK: $1
