#define yymaxdepth exparser_maxdepth
#define yyparse exparser_parse
#define yylex exparser_lex
#define yyerror exparser_error
#define yylval exparser_lval
#define yychar exparser_char
#define yydebug exparser_debug
#define yypact exparser_pact
#define yyr1 exparser_r1
#define yyr2 exparser_r2
#define yydef exparser_def
#define yychk exparser_chk
#define yypgo exparser_pgo
#define yyact exparser_act
#define yyexca exparser_exca
#define yyerrflag exparser_errflag
#define yynerrs exparser_nerrs
#define yyps exparser_ps
#define yypv exparser_pv
#define yys exparser_s
#define yy_yys exparser_yys
#define yystate exparser_state
#define yytmp exparser_tmp
#define yyv exparser_v
#define yy_yyv exparser_yyv
#define yyval exparser_val
#define yylloc exparser_lloc
#define yyreds exparser_reds
#define yytoks exparser_toks
#define yylhs exparser_yylhs
#define yylen exparser_yylen
#define yydefred exparser_yydefred
#define yydgoto exparser_yydgoto
#define yysindex exparser_yysindex
#define yyrindex exparser_yyrindex
#define yygindex exparser_yygindex
#define yytable exparser_yytable
#define yycheck exparser_yycheck          
#define yytable exparser_yytable
#define yycheck exparser_yycheck
#define yyname exparser_yyname
#define yyrule exparser_yyrule                                                  
